<?php

namespace App\Support;

class LabSettingsDefaults
{
    /**
     * @return array<string, mixed>
     */
    public static function labIdentity(): array
    {
        return [
            'name' => 'LaboSuite Diagnostics',
            'address' => '12 Medical Avenue, Casablanca',
            'phone' => '+212600000000',
            'email' => 'contact@labosuite.local',
            'header_note' => 'Trusted laboratory results',
            'footer_note' => 'Generated by LaboSuite',
            'header_info_position' => 'center',
            'header_logo_mode' => 'single_left',
            'header_logo_size_px' => 170,
            'header_logo_position_left' => 'center',
            'header_logo_position_right' => 'center',
            'logo_left_path' => null,
            'logo_right_path' => null,
        ];
    }

    /**
     * @return array<string, mixed>
     */
    public static function reportLayout(): array
    {
        return [
            'show_unit_column' => false,
            'highlight_abnormal' => true,
            'discipline_title_size' => 'text-xl',
            'category_title_size' => 'text-base',
            'report_font_family' => 'robotic',
            'report_lab_name_size_px' => 18,
            'report_lab_meta_size_px' => 13,
            'report_title_size_px' => 20,
            'report_patient_title_size_px' => 13,
            'report_patient_text_size_px' => 13,
            'report_table_header_size_px' => 12,
            'report_table_body_size_px' => 13,
            'report_level0_size_px' => 16,
            'report_level1_size_px' => 15,
            'report_level2_size_px' => 14,
            'report_level3_size_px' => 13,
            'report_leaf_size_px' => 13,
        ];
    }

    /**
     * @return array<string, mixed>
     */
    public static function uiAppearance(): array
    {
        return [
            // Keep legacy look as default (same typography as before advanced customization).
            'app_font_family' => 'legacy',
            'ui_font_size_level' => 'standard',
            'label_font_size_px' => 13,
            'label_font_weight' => '600',
            'label_letter_spacing_em' => 0.01,
            'label_text_transform' => 'none',
            'motion_profile' => 'soft',
        ];
    }
}
