<?php

namespace Database\Seeders;

use App\Models\LabSetting;
use Illuminate\Database\Seeder;

class LabSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        LabSetting::putValue('lab_identity', [
            'name' => 'LaboSuite Diagnostics',
            'address' => '12 Medical Avenue, Casablanca',
            'phone' => '+212600000000',
            'email' => 'contact@labosuite.local',
            'header_note' => 'Trusted laboratory results',
            'footer_note' => 'Generated by LaboSuite',
        ]);

        LabSetting::putValue('report_layout', [
            'show_unit_column' => false,
            'highlight_abnormal' => true,
            'discipline_title_size' => 'text-xl',
            'category_title_size' => 'text-base',
        ]);
    }
}
