<?php

namespace Database\Seeders;

use App\Models\LabSetting;
use Illuminate\Database\Seeder;

class LabSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $defaultIdentity = [
            'name' => 'LaboSuite Diagnostics',
            'address' => '12 Medical Avenue, Casablanca',
            'phone' => '+212600000000',
            'email' => 'contact@labosuite.local',
            'header_note' => 'Trusted laboratory results',
            'footer_note' => 'Generated by LaboSuite',
            'header_info_position' => 'center',
            'header_logo_mode' => 'single_left',
            'header_logo_size_px' => 170,
            'header_logo_offset_x_left' => 0,
            'header_logo_offset_x_right' => 0,
            'logo_left_path' => null,
            'logo_right_path' => null,
        ];

        $existingIdentity = LabSetting::getValue('lab_identity', []);
        if (! is_array($existingIdentity)) {
            $existingIdentity = [];
        }

        LabSetting::putValue('lab_identity', [
            ...$defaultIdentity,
            ...$existingIdentity,
        ]);

        $defaultReportLayout = [
            'show_unit_column' => false,
            'highlight_abnormal' => true,
            'discipline_title_size' => 'text-xl',
            'category_title_size' => 'text-base',
        ];

        $existingLayout = LabSetting::getValue('report_layout', []);
        if (! is_array($existingLayout)) {
            $existingLayout = [];
        }

        LabSetting::putValue('report_layout', [
            ...$defaultReportLayout,
            ...$existingLayout,
        ]);
    }
}
